name: GitHub Actions - Worflow Run Basic Template
run-name: Running - Worflow Run Basic Template
on: 
  workflow_run:
      workflows: [GitHub Actions - Trigger 1]
jobs:
  on-workflow_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: |
         echo "Worflow que foi trigado"