name: GitHub Actions - Configuração de Variáveis de Respositório
run-name: Running - Var Repo Config
on: [push, workflow_dispatch]
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: |
         echo "${{ vars.CURSO_GITHUB_ACTIONS }}"