name: GitHub Actions - Teste com dependência Template
run-name: Running - Teste com dependência Template
on: [push, workflow_dispatch]
  
jobs:
    test_unit:
      runs-on: ubuntu-latest
      steps:
        - name: Comentário
          run: |
           echo "Execução de Testes unitários"

    test_api:
      needs: test_unit
      runs-on: ubuntu-latest
      steps:
      - name: Comentário
        run: |
          echo "Execução de testes de API"


    test_ui:
      needs: [test_unit, test_api]
      runs-on: ubuntu-latest
      steps:
      - name: Comentário
        run: |
          echo "Execução de testes de Interface"
