name: GitHub Actions - Matriz strategy Template
run-name: Running - Matrix
on: [push, workflow_dispatch]
  
jobs:
    matrix_job:
      runs-on: ubuntu-latest
      strategy:
        matrix:
           navegador: [chrome, firefoz, webkit]  
        fail-fast: false   
      steps:
        - name: Comentário
          run: |
           echo "${{ matrix.navegador }}"
