name: GitHub Actions - Push Template basic
run-name: Running - ${{ github.event_name }}
on:
    push: 
     branches-ignore:
      - main
      - master

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: |
         echo "Comentário da Execução do Worflow"