name: GitHub Actions - Push Template basic
run-name: Running - ${{ github.event_name }}
on: [push]

jobs:
  on-push:
    runs-on: ubuntun-latest
    steps:
      - name: Comentário
        run: |
         echo "Comentário da Execução do Worflow"